# Generated by Django 4.1 on 2022-08-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='people',
        ),
    ]
