# Generated by Django 4.1 on 2022-08-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
